// EN ESTE ARCHIVO VA EL OBJETO DE LAS ACCIONES OSEA LOS NOMBRES DE LO QUE ARA LA APP
// ESTE TYPES SOLO HACE REFERENCIA AL REDUCER CONTADOR SI NECESITAMOS OTRO TYPE PARA OTRO REDUCER
// DIFERENTE ENTONCES SE CREA OTRO ARCHIVO CON OTROS TYPES QUE SOLO HAGA REFERENCIA A ESE ARCHIVO
export const TYPES={
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    INCREMENT_5:'INCREMENT5',
    DECREMENT_5:'DECREMENT5',
    RESET:'RESET'
}